# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3034f9287dc803b6bd79dcbda358fb6e988a34851a843f765d029605b3a04fc72edb8896d2bfca71d9ee51e8ce54bef0e313d0b76fcb05fea70bfc186bdc1782

test:
  secret_key_base: 81606c20cd5364c17a275bf714769b25aa8168fa625f293d266f2879b6df0b221e0ce98cf2e9736f698d4a2304e6972c3acdf206a3f66af4dad001f2fdced306

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
